import test from 'node:test';import assert from 'node:assert/strict';import {execFileSync} from 'node:child_process';import {mkdtempSync,mkdirSync,writeFileSync,readFileSync} from 'node:fs';import {tmpdir} from 'node:os';import {join} from 'node:path';import {Store} from '../src/store.ts';import {materializeCandidate,workflowSource} from '../src/workflow-candidates.ts';
function git(root:string,...args:string[]){return execFileSync('git',['-c','commit.gpgsign=false',...args],{cwd:root,encoding:'utf8',env:{...process.env,GIT_AUTHOR_NAME:'Fixture',GIT_AUTHOR_EMAIL:'fixture@example.invalid',GIT_COMMITTER_NAME:'Fixture',GIT_COMMITTER_EMAIL:'fixture@example.invalid'}}).trim();}
function fixture(){const root=mkdtempSync(join(tmpdir(),'wimzo-candidate-'));writeFileSync(join(root,'one.txt'),'one\n');writeFileSync(join(root,'two.txt'),'two\n');git(root,'init','-q');git(root,'add','.');git(root,'commit','-qm','baseline');return {root,base:git(root,'rev-parse','HEAD'),state:mkdtempSync(join(tmpdir(),'wimzo-candidate-state-'))};}
test('materialization preserves ordinary index and dirty worktree while retaining exact runnable source',async()=>{const f=fixture();writeFileSync(join(f.root,'one.txt'),'changed\n');git(f.root,'add','one.txt');writeFileSync(join(f.root,'two.txt'),'unstaged\n');writeFileSync(join(f.root,'new.txt'),'new\n');const status=git(f.root,'status','--porcelain'),index=git(f.root,'write-tree');const candidate=await materializeCandidate(f.root,{id:'sha256:fixture',baseCommit:f.base,dirty:true,specHash:'spec'},'fixture-run',f.state);assert.equal(git(f.root,'status','--porcelain'),status);assert.equal(git(f.root,'write-tree'),index);assert.equal(git(f.root,'rev-parse','HEAD'),f.base);assert.equal(git(f.root,'show',`${candidate.materializedCommit}:new.txt`),'new');assert.equal(git(f.root,'show',`${candidate.materializedCommit}:two.txt`),'unstaged');assert.equal(candidate.id,'sha256:fixture');assert.equal(Number(git(f.root,'show','-s','--format=%ct',candidate.materializedCommit)),Number(git(f.root,'show','-s','--format=%ct',f.base))+1);});
test('verified dependency candidates merge into isolated continuation source and reject stale receipts',async()=>{const f=fixture(),store=new Store(':memory:');try{const paths=['left','right'].map(name=>join(f.state,name));for(const path of paths)git(f.root,'worktree','add','--detach',path,f.base);writeFileSync(join(paths[0],'one.txt'),'left\n');writeFileSync(join(paths[1],'two.txt'),'right\n');const left=await materializeCandidate(paths[0],{id:'sha256:left',baseCommit:f.base,dirty:true,specHash:'s'},'left',f.state),right=await materializeCandidate(paths[1],{id:'sha256:right',baseCommit:f.base,dirty:true,specHash:'s'},'right',f.state);
 store.put('workflow_owner_approval',{id:'approval',projectId:'p',actor:{role:'owner'}});store.put('workflow_feature',{id:'feature',projectId:'p',approvalId:'approval'});
 const child={id:'child',projectId:'p',workflow:{featureId:'feature',purpose:'implementation_slice'},inheritedAuthorization:{ownerApprovalId:'approval'},dependencies:['left','right']};
 for(const [id,candidate] of [['left',left],['right',right]] as const){store.put('task',{id,projectId:'p',workflow:{featureId:'feature'},state:'Needs result review',dimensions:{verified:true},candidate,specId:'spec',specHash:'s'});store.put('workflow_continuation',{id:`workflow_continuation:${id}:child`,projectId:'p',featureId:'feature',ownerApprovalId:'approval',successorTaskId:'child',candidate,specId:'spec',specHash:'s'});}
 const source=await workflowSource(store,child,f.root);assert.ok(source);assert.equal(git(f.root,'show',`${source.commit}:one.txt`),'left');assert.equal(git(f.root,'show',`${source.commit}:two.txt`),'right');assert.equal(git(f.root,'rev-parse','HEAD'),f.base);assert.equal((await workflowSource(store,child,f.root))?.commit,source.commit);assert.equal(Number(git(f.root,'show','-s','--format=%ct',source.commit)),Number(git(f.root,'show','-s','--format=%ct',left.materializedCommit))+1);
 const before=store.require('task','left');store.put('task',{...before,candidate:{...left,id:'changed'}},before.rev);await assert.rejects(workflowSource(store,child,f.root),/candidate changed/);
 }finally{store.close();}});
test('verification resolves only its exact same-feature materialized candidate',async()=>{const f=fixture(),store=new Store(':memory:');try{store.put('workflow_owner_approval',{id:'a',projectId:'p',actor:{role:'owner'}});store.put('workflow_feature',{id:'feature',projectId:'p',approvalId:'a'});const candidate={id:f.base,materializedCommit:f.base,specHash:'s'};store.put('task',{id:'target',projectId:'p',workflow:{featureId:'feature'},state:'Verifying',candidate});const task={id:'verifier',projectId:'p',inheritedAuthorization:{ownerApprovalId:'a'},workflow:{featureId:'feature',purpose:'verification',targetTaskId:'target',targetCandidate:candidate}};assert.equal((await workflowSource(store,task,f.root))?.commit,f.base);await assert.rejects(workflowSource(store,{...task,projectId:'other'},f.root),/exact feature approval/);}finally{store.close();}});
