import { App } from './app.ts';
import { readFileSync } from 'node:fs';
import { createInterface } from 'node:readline';
import { workerContext, readWorkerSpecification, saveWorkerCheckpoint } from './worker-context.ts';
import { assertProfileRouteAuthorized } from './worker-profile.ts';
import { assert } from './store.ts';

export function scopedWorkerTools(app:App,taskId:string,runId:string) {
 const bound=()=>{const t=app.store.require('task',taskId);assert(t.runId===runId&&t.state==='Running','This worker run is no longer active');assert(t.controller?.kind!=='human'&&t.requested?.command!=='takeover','Human takeover has stopped agent input');assertProfileRouteAuthorized(app.store,t);return t;};
 const definitions:any[]=[
 {name:'wimzo_context',description:'Read the exact task, accepted PRD and latest durable handoff.',annotations:{readOnlyHint:true,destructiveHint:false},inputSchema:{type:'object',properties:{},additionalProperties:false}},
 {name:'wimzo_specification',description:'Read a bounded page of one exact accepted specification in this task’s immutable owner-approved scope.',annotations:{readOnlyHint:true,destructiveHint:false},inputSchema:{type:'object',required:['specId'],properties:{specId:{type:'string'},offset:{type:'integer',minimum:0},maxChars:{type:'integer',minimum:1,maximum:30000}},additionalProperties:false}},
 {name:'wimzo_checkpoint',description:'Save meaningful progress, exact checks, candidate and next steps before continuing or stopping.',annotations:{readOnlyHint:false,destructiveHint:false},inputSchema:{type:'object',required:['summary'],properties:{summary:{type:'string'},next:{type:'string'},checks:{type:'array',items:{type:'object'}},candidate:{type:'object'},submissionId:{type:'string'},changelog:{type:'object',description:'Plain-language account for the owner: what changed, what is possible now, availability and limits. Never claim a release.',properties:{changed:{type:'string'},possibleNow:{type:'string'},availability:{type:'string'},limits:{type:'array',items:{type:'string'}}},additionalProperties:false}},additionalProperties:false}},
 {name:'wimzo_phase',description:'Report the actual current planning or implementation phase.',annotations:{readOnlyHint:false,destructiveHint:false},inputSchema:{type:'object',required:['phase'],properties:{phase:{type:'string',enum:['planning','implementing']},note:{type:'string'}},additionalProperties:false}}
 ];
 const configured=app.store.require<any>('task',taskId);const featureId=typeof configured.workflow?.featureId==='string'?configured.workflow.featureId:null;
 if(featureId)definitions.push(
  {name:'wimzo_workflow_draft_context',description:'Read exact prior virtual PRD drafts and revision notes for this task-bound workflow feature.',annotations:{readOnlyHint:true,destructiveHint:false},inputSchema:{type:'object',properties:{},additionalProperties:false}},
  {name:'wimzo_workflow_propose_requirements',description:'Persist exact proposed PRD amendments for owner review. This does not accept requirements.',annotations:{readOnlyHint:false,destructiveHint:false},inputSchema:{type:'object',required:['changes','revisionNote','submissionId'],properties:{changes:{type:'array',items:{type:'object'}},revisionNote:{type:'string'},summary:{type:'string'},submissionId:{type:'string'}},additionalProperties:false}},
  {name:'wimzo_workflow_submit_plan',description:'Save a bounded implementation plan that remains within the approved workflow task.',annotations:{readOnlyHint:false,destructiveHint:false},inputSchema:{type:'object',required:['slices','submissionId'],properties:{slices:{type:'array',items:{type:'object'}},submissionId:{type:'string'}},additionalProperties:false}},
  {name:'wimzo_workflow_progress',description:'Record a bounded progress note for this active workflow task.',annotations:{readOnlyHint:false,destructiveHint:false},inputSchema:{type:'object',required:['summary'],properties:{summary:{type:'string'}},additionalProperties:false}},
  {name:'wimzo_workflow_continuation',description:'Read exact verified dependency candidates for this task-bound workflow successor.',annotations:{readOnlyHint:true,destructiveHint:false},inputSchema:{type:'object',properties:{},additionalProperties:false}},
 );
 if(configured.workflow?.purpose==='verification')definitions.push({name:'wimzo_workflow_submit_verification',description:'Persist exact read-only verification evidence for this task’s assigned implementation candidate.',annotations:{readOnlyHint:false,destructiveHint:false},inputSchema:{type:'object',required:['candidate','checks','summary','submissionId'],properties:{candidate:{type:'object'},checks:{type:'array',items:{type:'object'}},summary:{type:'string'},submissionId:{type:'string'}},additionalProperties:false}});
 async function invoke(name:string,input:any={}) {const t=bound();const actor={role:'worker' as const,id:t.workerId??`execution:${taskId}`,taskId};const currentFeature=typeof t.workflow?.featureId==='string'?t.workflow.featureId:null;if(name==='wimzo_context')return workerContext(app.store,taskId,runId);if(name==='wimzo_specification')return readWorkerSpecification(app.store,taskId,runId,input);if(name==='wimzo_checkpoint')return saveWorkerCheckpoint(app.store,taskId,runId,input);if(name==='wimzo_phase')return app.call('board.phase',{...input,taskId,expectedRev:t.rev},actor);assert(currentFeature,'Workflow tools are unavailable for this task');if(name==='wimzo_workflow_draft_context')return app.call('workflow.draftContext',{featureId:currentFeature,taskId},actor);if(name==='wimzo_workflow_propose_requirements')return app.call('workflow.proposeRequirements',{...input,featureId:currentFeature,taskId,expectedTaskRev:t.rev},actor);if(name==='wimzo_workflow_submit_plan')return app.call('workflow.submitPlan',{...input,featureId:currentFeature,taskId,expectedTaskRev:t.rev},actor);if(name==='wimzo_workflow_progress')return app.call('workflow.progress',{...input,featureId:currentFeature,taskId,expectedTaskRev:t.rev},actor);if(name==='wimzo_workflow_continuation')return app.call('workflow.continuation',{featureId:currentFeature,taskId},actor);if(name==='wimzo_workflow_submit_verification'){assert(t.workflow?.purpose==='verification'&&typeof t.workflow?.targetTaskId==='string','Verification tool is unavailable for this task');return app.call('workflow.submitVerification',{...input,featureId:currentFeature,taskId,expectedTaskRev:t.rev,targetTaskId:t.workflow.targetTaskId},actor);}throw new Error('Tool is not available to this worker');}
 return {definitions,invoke};
}
export async function serveWorkerBridge(config:any) {
 const app=new App(config.stateDir),tools=scopedWorkerTools(app,config.taskId,config.runId);
 const lines=createInterface({input:process.stdin,crlfDelay:Infinity});let queue=Promise.resolve();
 const send=(value:any)=>process.stdout.write(JSON.stringify(value)+'\n');
 const handle=async(line:string)=>{let request:any;try{assert(line.length<=100000,'Worker tool request is too large');request=JSON.parse(line);if(request.id===undefined)return;let result:any;if(request.method==='initialize')result={protocolVersion:'2024-11-05',capabilities:{tools:{}},serverInfo:{name:'wimzo-worker',version:'1.0'}};else if(request.method==='tools/list')result={tools:tools.definitions};else if(request.method==='tools/call'){const value=await tools.invoke(request.params.name,request.params.arguments);result={content:[{type:'text',text:JSON.stringify(value)}]};}else if(request.method==='ping')result={};else throw new Error('Unknown worker bridge operation');send({jsonrpc:'2.0',id:request.id,result});}catch(error){send({jsonrpc:'2.0',id:request?.id??null,error:{code:-32602,message:String((error as Error).message)}});}};
 lines.on('line',line=>{queue=queue.then(()=>handle(line));});await new Promise<void>(done=>lines.on('close',()=>{queue.finally(done)}));await app.close();
}
if(process.argv[1]===import.meta.filename){const config=JSON.parse(readFileSync(process.argv[2],'utf8'));await serveWorkerBridge(config);}
